version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: leadertask
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: leadertask
      SQLALCHEMY_DATABASE_URL: postgresql://postgres:qwerty@db/leadertask
      MONGO_URI: mongodb://mongo:27017/
    depends_on:
      - db
      - mongo
    command: >
      sh -c "sleep 10 && python mongo_db.py && python pg_db.py && uvicorn jwt:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/app

volumes:
  postgres_data:
  mongo_data:
